{
 "title": "geral",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Trocas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sorting_swaps_total{algorithm=\"BubbleSort\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sorting_swaps_total{algorithm=\"TimSort\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sorting_swaps_total{algorithm=\"QuickSort\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Comparações",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sorting_comparisons_total{algorithm=\"BubbleSort\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sorting_comparisons_total{algorithm=\"TimSort\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sorting_comparisons_total{algorithm=\"QuickSort\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tempo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(sorting_execution_time_seconds_sum{algorithm=\"BubbleSort\"}[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(sorting_execution_time_seconds_sum{algorithm=\"TimSort\"}[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(sorting_execution_time_seconds_sum{algorithm=\"QuickSort\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}